# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwW_ICKJrPGX3hjyns40CKnmWrGU2Wx3
"""

import pandas as pd
baza = {
    "FISH": ["Aliiyev Ali", "Aliyeva Dilyora", "Aliyev Sirojiddin", "Olimjonov Muhammadali", "Mo'ydinjonov Muhammadziyo", "Ahmadova Mohigul", "Akramov Iqbol", "Mo'ydinjonova Durdonaxon", "Abdurhimova Mubiyna", "Rahmonvazarova Sanamxon"],
    "Yoshi": [11, 16, 17, 12, 13, 15, 12, 14, 16, 17],
    "Jinsi": ['erkak', 'ayol', 'erkak', 'erkak', 'erkak', 'ayol', 'erkak', 'ayol', 'ayol', 'ayol'],
    "Maktabi": ["2-maktab", "Prezindent maktabi", "23-maktab", "13-maktab", "14-maktab", "15-maktab", "16-maktab", "17-maktab", "23-maktab", "33-maktab"],
    "Manzili": ["Farg'ona shahar",  "Andijon shahar", "Qo'qon shahri", "Farg'ona shahar",  "Andijon shahar", "Qo'qon shahri", "Farg'ona shahar",  "Andijon shahar", "Qo'qon shahri", "Toshkent shahri"],
    "Tel raqami": ["99 302 22 12", "90 123 45 67", "90 234 56 23", "99 302 22 12", "91 123 45 67", "93 234 56 23", "91 302 22 12", "99 123 45 67", "93 234 56 23", "90 369 90 12"]

}

db = pd.DataFrame(baza)
print(db)

filtr = db[(db['Jinsi'] == 'ayol') &
           (db['Yoshi'] >= 15) &
           (db['Tel raqami'].str.startswith('90'))]

print(filtr)